/*
 * SPDX-FileCopyrightText: 2026 The LineageOS Project
 * SPDX-License-Identifier: Apache-2.0
 */

// SPDX-License-Identifier: Apache-2.0
//
// bootsplash — the animation that fills the black gap between the kernel and
// the LineageOS bootanimation (§43).
//
// The black gap, measured on the tablet: from 1.171 s — when exynos-drm binds
// the DECON and the scanout inherited from the bootloader stops — until
// 20.8 s, when SurfaceFlinger does its modeset and the bootanimation starts.
// Twenty seconds in which the panel is on and shows nothing (§25.1).
//
// This program draws the LineageOS animation — three rotating dots — at the
// same position and with the same frames as the bootanimation. The image is
// in `anim.rle`, generated by `tools/make-bootsplash-anim.py` from the
// build's bootanimation, and linked into the binary with .incbin.
//
// Constraints from which everything else follows:
//
//  - It runs in FIRST STAGE, inside the ramdisk, before SwitchRoot. After the
//    switch its "/" is the old root and /dev has been moved: so the program
//    waits for and opens the DRM card BEFORE notifying generic_init through
//    --ready-fd, and from then on it no longer touches the filesystem. No
//    dynamic libraries (static binary), no libpng, no libz.
//
//  - After the modeset it drops master (DROP_MASTER). Scanout continues —
//    the CRTC is not turned off — but SurfaceFlinger can take the display
//    when it arrives, without finding the door locked. The animation goes on
//    by writing into the mapped buffer, which does not require being master.
//
//  - SELinux switches to enforcing while the process is alive (init second
//    stage). The process stays in the `kernel` domain, so after the modeset
//    it makes no call that the policy would have to allow: only writes to
//    already-mapped memory and clock_nanosleep. /dev/kmsg is also closed
//    before the loop.
//
// It runs at two different times:
//
//  - at boot, launched by generic_init in first stage (the main case);
//  - when leaving charging mode, when the key is pressed to continue into
//    Android: there the kernel has been up for a while, the charger releases
//    the display and nobody draws anything until SurfaceFlinger. init
//    restarts it on `sys.boot_from_charger_mode=1`, as a vendor service with
//    its own domain (§43.11).
//
// Outside of boot it can be tried by hand, as was done for the charger in
// §30.6:
//
//     adb push out/.../ramdisk/system/bin/bootsplash /vendor/bin/   # overlay rw
//     adb shell setprop ctl.stop surfaceflinger
//     adb shell /vendor/bin/bootsplash --seconds=15
//     adb shell setprop ctl.start surfaceflinger

#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/sysmacros.h>
#include <time.h>
#include <unistd.h>

#include <drm/drm.h>
#include <drm/drm_mode.h>

// ----------------------------------------------------------------- animation

extern const unsigned char _binary_anim_rle_start[];
extern const unsigned char _binary_anim_rle_end[];

#define ANIM_MAGIC 0x4c505347u /* "GSPL" */

struct anim_header {
    unsigned int magic;
    unsigned int version;
    unsigned int width;
    unsigned int height;
    unsigned int n_frames;
    unsigned int loop_start;
    unsigned int fps;
    unsigned int rle_length;
};

// ---------------------------------------------------------------- utilities

static int kmsg_fd = -1;

static void klog(const char* fmt, ...) {
    if (kmsg_fd < 0) return;
    char buf[512];
    int n = snprintf(buf, sizeof(buf), "bootsplash: ");
    va_list ap;
    va_start(ap, fmt);
    n += vsnprintf(buf + n, sizeof(buf) - (size_t)n - 1, fmt, ap);
    va_end(ap);
    if (n > 0 && (size_t)n < sizeof(buf) - 1) {
        buf[n++] = '\n';
        (void)!write(kmsg_fd, buf, (size_t)n);
    }
}

static long long now_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

static void sleep_ms(long long ms) {
    if (ms <= 0) return;
    struct timespec ts = {.tv_sec = ms / 1000, .tv_nsec = (ms % 1000) * 1000000};
    while (nanosleep(&ts, &ts) < 0 && errno == EINTR) {
    }
}

// How long everything before the kernel took.
//
// The ARM architected counter starts with the SoC and nobody resets it,
// while CLOCK_MONOTONIC starts at zero when the kernel initialises
// timekeeping: the difference is the time spent in S-BOOT and the loader, which
// is otherwise visible nowhere: neither has a console (§33.8, §73).
// On this SoC CNTFRQ_EL0 reads ZERO: the firmware does not program it, and
// that is exactly why the device tree declares timer/clock-frequency
// (26 MHz). Asking only the register gave -1.
static unsigned long long counter_frequency(void) {
    unsigned long long frq = 0;
    __asm__ volatile("mrs %0, cntfrq_el0" : "=r"(frq));
    if (frq) return frq;

    int fd = open("/sys/firmware/devicetree/base/timer/clock-frequency",
                  O_RDONLY | O_CLOEXEC);
    if (fd < 0) return 0;
    unsigned char b[4] = {0};
    ssize_t n = read(fd, b, sizeof(b));
    close(fd);
    if (n != 4) return 0;
    return ((unsigned long long)b[0] << 24) | ((unsigned long long)b[1] << 16) |
           ((unsigned long long)b[2] << 8) | b[3];  // the DT is big-endian
}

#if defined(__aarch64__)
static long long ms_before_kernel(void) {
    unsigned long long count;
    __asm__ volatile("mrs %0, cntvct_el0" : "=r"(count));
    unsigned long long frequency = counter_frequency();
    if (frequency == 0) return -1;
    return (long long)(count * 1000ULL / frequency) - now_ms();
}
#else
static long long ms_before_kernel(void) {
    return -1;
}
#endif

static volatile sig_atomic_t stop_requested = 0;

static void on_signal(int sig) {
    (void)sig;
    stop_requested = 1;
}

// ---------------------------------------------------------------------- DRM

struct screen {
    int fd;
    unsigned int connector;
    unsigned int crtc;
    struct drm_mode_modeinfo mode;

    unsigned int handle;
    unsigned int fb;
    unsigned int pitch;
    unsigned long long size;
    unsigned char* pixel;
};

static int drm_ioctl(int fd, unsigned long request, void* arg) {
    int ret;
    do {
        ret = ioctl(fd, request, arg);
    } while (ret < 0 && (errno == EINTR || errno == EAGAIN));
    return ret;
}

// A card is good if it actually drives a panel: on this tablet exynos-drm
// (DECON+DSI, the only one with a connector) and panfrost (render only)
// coexist. The criterion is the same as androidboot.prefer_drm_card_name on
// the cmdline, but measured instead of by name: cards without connectors are
// discarded.
static int card_is_usable(int fd, const char* label) {
    char name[32] = {0};
    struct drm_version v;
    memset(&v, 0, sizeof(v));
    v.name = name;
    v.name_len = sizeof(name) - 1;
    if (drm_ioctl(fd, DRM_IOCTL_VERSION, &v) < 0) return -1;

    struct drm_mode_card_res res;
    memset(&res, 0, sizeof(res));
    if (drm_ioctl(fd, DRM_IOCTL_MODE_GETRESOURCES, &res) < 0 ||
        res.count_connectors == 0) {
        klog("%s (%s): no connectors, discarded", label, name);
        return -1;
    }

    klog("card %s: %s, %u connectors", label, name,
         res.count_connectors);
    return 0;
}

// The node we need, when ueventd has not created it yet.
//
// Measured on 19/09: exynos-drm registers at 1.18 s, but /dev/dri/card0
// only appears at ~4.1 s, at the end of ueventd's cold-boot scan. Two and a
// half seconds of black that have nothing to do with the hardware. In /sys,
// however, the device number is there right away, and a mknod costs nothing:
// the splash creates its own node, opens it and deletes it. It does not touch
// /dev/dri, which stays entirely ueventd's; the open file survives the
// unlink.
static int open_from_sysfs(int i) {
    char path[64];
    snprintf(path, sizeof(path), "/sys/class/drm/card%d/dev", i);

    int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return -1;
    char buf[32] = {0};
    ssize_t n = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (n <= 0) return -1;

    unsigned int dev_major = 0, dev_minor = 0;
    if (sscanf(buf, "%u:%u", &dev_major, &dev_minor) != 2) return -1;

    const char* node = "/dev/.bootsplash-card";
    unlink(node);
    if (mknod(node, S_IFCHR | 0600, makedev(dev_major, dev_minor)) != 0) return -1;

    fd = open(node, O_RDWR | O_CLOEXEC);
    unlink(node);
    if (fd < 0) return -1;

    char label[64];
    snprintf(label, sizeof(label), "sysfs card%d (%u:%u)", i, dev_major,
             dev_minor);
    if (card_is_usable(fd, label) < 0) {
        close(fd);
        return -1;
    }
    return fd;
}

static int open_card_once(const char* explicit_path) {
    if (explicit_path) {
        int fd = open(explicit_path, O_RDWR | O_CLOEXEC);
        if (fd < 0) return -1;
        if (card_is_usable(fd, explicit_path) < 0) {
            close(fd);
            return -1;
        }
        return fd;
    }

    for (int i = 0; i < 8; i++) {
        // The real node first, if it exists: that is the case when we run on
        // a booted system (leaving charging mode, §43.11). The sysfs path is
        // only needed in first stage, where /dev/dri does not exist yet, and
        // it goes through a mknod that on a booted system would cost two
        // denials — one on sysfs_gpu and one on the sys_admin capability —
        // for nothing.
        char path[64];
        snprintf(path, sizeof(path), "/dev/dri/card%d", i);
        int fd = open(path, O_RDWR | O_CLOEXEC);
        if (fd >= 0) {
            if (card_is_usable(fd, path) == 0) return fd;
            close(fd);
            continue;
        }

        fd = open_from_sysfs(i);
        if (fd >= 0) return fd;
    }
    return -1;
}

// generic_init launches the splash before the first ueventd, so that it
// draws as soon as the node exists instead of waiting for the end of the
// scan (§43): hence the wait here. The limit is generous because the only one
// really waiting is the splash — generic_init moves on after 2 s.
static int open_card(const char* explicit_path, int wait_ms) {
    long long deadline = now_ms() + wait_ms;
    for (;;) {
        int fd = open_card_once(explicit_path);
        if (fd >= 0) return fd;
        if (now_ms() >= deadline) return -1;
        sleep_ms(20);
    }
}

// First connected connector with at least one mode, and the CRTC serving it.
static int find_output(struct screen* s) {
    struct drm_mode_card_res res;
    memset(&res, 0, sizeof(res));
    if (drm_ioctl(s->fd, DRM_IOCTL_MODE_GETRESOURCES, &res) < 0) return -1;

    unsigned int conn_id[32], crtc_id[32];
    if (res.count_connectors > 32 || res.count_crtcs > 32) return -1;
    res.connector_id_ptr = (unsigned long long)(uintptr_t)conn_id;
    res.crtc_id_ptr = (unsigned long long)(uintptr_t)crtc_id;
    res.fb_id_ptr = 0;
    res.encoder_id_ptr = 0;
    res.count_fbs = 0;
    res.count_encoders = 0;
    if (drm_ioctl(s->fd, DRM_IOCTL_MODE_GETRESOURCES, &res) < 0) return -1;

    for (unsigned int i = 0; i < res.count_connectors; i++) {
        struct drm_mode_get_connector c;
        memset(&c, 0, sizeof(c));
        c.connector_id = conn_id[i];
        if (drm_ioctl(s->fd, DRM_IOCTL_MODE_GETCONNECTOR, &c) < 0) continue;
        if (c.connection != 1 /* connected */ || c.count_modes == 0) continue;

        struct drm_mode_modeinfo modes[32];
        unsigned int encoder_id[16];
        unsigned int n_modes = c.count_modes > 32 ? 32 : c.count_modes;
        unsigned int n_enc = c.count_encoders > 16 ? 16 : c.count_encoders;
        memset(modes, 0, sizeof(modes));
        c.modes_ptr = (unsigned long long)(uintptr_t)modes;
        c.count_modes = n_modes;
        c.encoders_ptr = (unsigned long long)(uintptr_t)encoder_id;
        c.count_encoders = n_enc;
        c.props_ptr = 0;
        c.prop_values_ptr = 0;
        c.count_props = 0;
        if (drm_ioctl(s->fd, DRM_IOCTL_MODE_GETCONNECTOR, &c) < 0) continue;
        if (c.count_modes == 0) continue;

        // The preferred mode is the first one the kernel lists.
        s->connector = conn_id[i];
        s->mode = modes[0];

        // The CRTC: the one already attached to the active encoder, otherwise
        // the first compatible one.
        unsigned int crtc = 0;
        if (c.encoder_id) {
            struct drm_mode_get_encoder e;
            memset(&e, 0, sizeof(e));
            e.encoder_id = c.encoder_id;
            if (drm_ioctl(s->fd, DRM_IOCTL_MODE_GETENCODER, &e) == 0) {
                crtc = e.crtc_id;
                if (!crtc) {
                    for (unsigned int k = 0; k < res.count_crtcs; k++) {
                        if (e.possible_crtcs & (1u << k)) {
                            crtc = crtc_id[k];
                            break;
                        }
                    }
                }
            }
        }
        if (!crtc && n_enc > 0) {
            struct drm_mode_get_encoder e;
            memset(&e, 0, sizeof(e));
            e.encoder_id = encoder_id[0];
            if (drm_ioctl(s->fd, DRM_IOCTL_MODE_GETENCODER, &e) == 0) {
                for (unsigned int k = 0; k < res.count_crtcs; k++) {
                    if (e.possible_crtcs & (1u << k)) {
                        crtc = crtc_id[k];
                        break;
                    }
                }
            }
        }
        if (!crtc && res.count_crtcs > 0) crtc = crtc_id[0];
        if (!crtc) continue;

        s->crtc = crtc;
        klog("connector %u, crtc %u, mode %ux%u@%u", s->connector, s->crtc,
             s->mode.hdisplay, s->mode.vdisplay, s->mode.vrefresh);
        return 0;
    }
    klog("no connected connector with a mode");
    return -1;
}

static int create_buffer(struct screen* s) {
    struct drm_mode_create_dumb dumb;
    memset(&dumb, 0, sizeof(dumb));
    dumb.width = s->mode.hdisplay;
    dumb.height = s->mode.vdisplay;
    dumb.bpp = 32;
    if (drm_ioctl(s->fd, DRM_IOCTL_MODE_CREATE_DUMB, &dumb) < 0) {
        klog("CREATE_DUMB: %s", strerror(errno));
        return -1;
    }
    s->handle = dumb.handle;
    s->pitch = dumb.pitch;
    s->size = dumb.size;

    struct drm_mode_fb_cmd fb;
    memset(&fb, 0, sizeof(fb));
    fb.width = s->mode.hdisplay;
    fb.height = s->mode.vdisplay;
    fb.pitch = s->pitch;
    fb.bpp = 32;
    fb.depth = 24;
    fb.handle = s->handle;
    if (drm_ioctl(s->fd, DRM_IOCTL_MODE_ADDFB, &fb) < 0) {
        klog("ADDFB: %s", strerror(errno));
        return -1;
    }
    s->fb = fb.fb_id;

    struct drm_mode_map_dumb map_req;
    memset(&map_req, 0, sizeof(map_req));
    map_req.handle = s->handle;
    if (drm_ioctl(s->fd, DRM_IOCTL_MODE_MAP_DUMB, &map_req) < 0) {
        klog("MAP_DUMB: %s", strerror(errno));
        return -1;
    }
    void* p = mmap(NULL, (size_t)s->size, PROT_READ | PROT_WRITE,
                   MAP_SHARED, s->fd, (off_t)map_req.offset);
    if (p == MAP_FAILED) {
        klog("mmap: %s", strerror(errno));
        return -1;
    }
    s->pixel = p;
    memset(s->pixel, 0, (size_t)s->size);
    return 0;
}

// The modeset, with retries.
//
// At boot we are alone and it succeeds on the first try. When leaving
// charging mode it does not: init stops the charger and starts us at the same
// instant, and until the charger has closed its fd master is still its own —
// SETCRTC answers "permission denied". One second of retries is more than
// enough, and if it really does not free up we give up without doing damage.
static int set_mode(struct screen* s, int wait_ms) {
    long long deadline = now_ms() + wait_ms;

    for (;;) {
        struct drm_mode_crtc set;
        memset(&set, 0, sizeof(set));
        set.crtc_id = s->crtc;
        set.fb_id = s->fb;
        set.set_connectors_ptr = (unsigned long long)(uintptr_t)&s->connector;
        set.count_connectors = 1;
        set.mode = s->mode;
        set.mode_valid = 1;
        if (drm_ioctl(s->fd, DRM_IOCTL_MODE_SETCRTC, &set) == 0) {
            return 0;
        }

        if (now_ms() >= deadline) {
            klog("SETCRTC: %s", strerror(errno));
            return -1;
        }
        sleep_ms(50);
    }
}

// ------------------------------------------------------------------ drawing

// Expands the RLE stream (count, value) into one luminance byte per pixel.
static int expand_rle(const unsigned char* rle, size_t n_rle, unsigned char* out,
                      size_t n_out) {
    size_t i = 0, o = 0;
    while (i + 1 < n_rle) {
        unsigned int n = rle[i];
        unsigned char v = rle[i + 1];
        i += 2;
        if (n == 0 || o + n > n_out) return -1;
        memset(out + o, v, n);
        o += n;
    }
    return o == n_out ? 0 : -1;
}

// Draws a frame by writing ONLY the pixels that change.
//
// This is not an optimisation, it is the fix for a visible defect: the panel
// is reading the same buffer while we write it, and without master we can
// neither page flip nor wait for vblank — a vblank wait would be one ioctl
// per frame, i.e. repeated SELinux denials once the policy is loaded.
// Rewriting all 300x100 pixels (120 KB) opens a tearing window as long as
// the scanout's pass over the region, and the dots flicker. Comparing with
// the previous frame reduces the write to a few hundred pixels: the window
// shrinks to microseconds and the tearing disappears.
//
// `prev_frame` is what is actually on screen: NULL means "unknown", and then
// everything is rewritten.
static void draw_frame(struct screen* s, const unsigned char* gray,
                       unsigned char* prev_frame, unsigned int w,
                       unsigned int h, int x0, int y0) {
    for (unsigned int y = 0; y < h; y++) {
        unsigned int* row =
                (unsigned int*)(s->pixel + (size_t)(y0 + (int)y) * s->pitch) + x0;
        const unsigned char* src = gray + (size_t)y * w;
        unsigned char* prev_row = prev_frame ? prev_frame + (size_t)y * w : NULL;

        for (unsigned int x = 0; x < w; x++) {
            unsigned int v = src[x];

            if (prev_row && prev_row[x] == (unsigned char)v)
                continue;

            row[x] = 0xff000000u | (v << 16) | (v << 8) | v;
            if (prev_row)
                prev_row[x] = (unsigned char)v;
        }
    }
}

// --------------------------------------------------------------------- main

int main(int argc, char** argv) {
    const char* card_path = NULL;
    int ready_fd = -1;
    int seconds = 45;
    int fps_override = 0;
    int card_wait_ms = 12000;
    int modeset_wait_ms = 3000;
    int still = 0;

    for (int i = 1; i < argc; i++) {
        if (!strncmp(argv[i], "--card=", 7)) {
            card_path = argv[i] + 7;
        } else if (!strncmp(argv[i], "--ready-fd=", 11)) {
            ready_fd = atoi(argv[i] + 11);
        } else if (!strncmp(argv[i], "--seconds=", 10)) {
            seconds = atoi(argv[i] + 10);
        } else if (!strncmp(argv[i], "--fps=", 6)) {
            fps_override = atoi(argv[i] + 6);
        } else if (!strncmp(argv[i], "--card-wait-ms=", 15)) {
            card_wait_ms = atoi(argv[i] + 15);
        } else if (!strncmp(argv[i], "--modeset-wait-ms=", 18)) {
            modeset_wait_ms = atoi(argv[i] + 18);
        } else if (!strcmp(argv[i], "--still")) {
            // Diagnostics: draw one frame and never touch the buffer again.
            // If the image still comes and goes, it is not our writes.
            still = 1;
        } else {
            fprintf(stderr,
                    "usage: %s [--card=/dev/dri/cardN] [--ready-fd=N] "
                    "[--seconds=N] [--fps=N] [--card-wait-ms=N]\n"
                    "       [--modeset-wait-ms=N] [--still]\n",
                    argv[0]);
            return 2;
        }
    }

    signal(SIGTERM, on_signal);
    signal(SIGINT, on_signal);
    signal(SIGPIPE, SIG_IGN);

    kmsg_fd = open("/dev/kmsg", O_WRONLY | O_CLOEXEC);

    // Measuring how long everything before the kernel took only makes sense
    // in first stage. When we restart on a booted system (leaving charging
    // mode, §43.11) it would give -1 and on top of that cost two denials: the
    // read of timer/clock-frequency in sysfs and the capability the kernel
    // checks right after. It is only queried if we have just started.
    if (now_ms() < 10000) {
        klog("before the kernel (S-BOOT + loader): %lld ms",
             ms_before_kernel());
    }

    struct screen s;
    memset(&s, 0, sizeof(s));
    s.fd = open_card(card_path, card_wait_ms);

    // From here on the filesystem is no longer touched: generic_init can go
    // ahead with SwitchRoot, which moves /dev under the new root.
    if (ready_fd >= 0) {
        (void)!write(ready_fd, "R", 1);
        close(ready_fd);
    }

    if (s.fd < 0) {
        klog("no usable DRM card");
        return 1;
    }

    const struct anim_header* a =
            (const struct anim_header*)_binary_anim_rle_start;
    if (a->magic != ANIM_MAGIC || a->version != 1) {
        klog("anim.rle: invalid header");
        return 1;
    }
    size_t n_pixel = (size_t)a->width * a->height * a->n_frames;
    unsigned char* frames = malloc(n_pixel);
    if (!frames ||
        expand_rle(_binary_anim_rle_start + sizeof(*a), a->rle_length,
                   frames, n_pixel) < 0) {
        klog("anim.rle: inconsistent RLE stream");
        return 1;
    }

    if (find_output(&s) < 0) return 1;
    if (create_buffer(&s) < 0) return 1;

    // The first frame before the modeset: the screen never goes through an
    // undefined background.
    int w = (int)a->width, h = (int)a->height;
    int x0 = ((int)s.mode.hdisplay - w) / 2;
    int y0 = ((int)s.mode.vdisplay - h) / 2;
    if (x0 < 0 || y0 < 0) {
        klog("mode %ux%u smaller than the animation %dx%d",
             s.mode.hdisplay, s.mode.vdisplay, w, h);
        return 1;
    }
    unsigned char* on_screen = malloc((size_t)w * h);
    if (on_screen)
        memcpy(on_screen, frames, (size_t)w * h);
    draw_frame(&s, frames, NULL, (unsigned)w, (unsigned)h, x0, y0);

    if (set_mode(&s, modeset_wait_ms) < 0) return 1;

    // Dropping master is the important half: without it, SurfaceFlinger
    // cannot take the display when it arrives. Scanout does not stop.
    if (drm_ioctl(s.fd, DRM_IOCTL_DROP_MASTER, NULL) < 0) {
        klog("DROP_MASTER: %s (continuing)", strerror(errno));
    }

    klog("on: %ux%u, animation %dx%d at %u fps, %u frames "
         "(loop from %u), for %d s",
         s.mode.hdisplay, s.mode.vdisplay, w, h, a->fps, a->n_frames,
         a->loop_start, seconds);

    // From here on, no call that SELinux would have to allow.
    if (kmsg_fd >= 0) {
        close(kmsg_fd);
        kmsg_fd = -1;
    }

    unsigned int fps = fps_override > 0 ? (unsigned)fps_override : a->fps;
    if (fps == 0) fps = 60;
    long long t0 = now_ms();
    long long deadline = t0 + (long long)seconds * 1000;

    unsigned int loop_len = a->n_frames - a->loop_start;

    // Alignment with the bootanimation, which will pick up where we leave off
    // (§43.8). The shared rule is: inside the loop, the frame index is
    // (monotonic time * fps / 1000) modulo the loop length. For it to hold
    // for us too, the intro must end when that count is an exact multiple of
    // the loop length.
    //
    // The speed is NOT changed to achieve this: stretching or shortening the
    // intro is visible, tried. The starting point is moved instead: either we
    // start a few frames later — the first frames of the fade-in are black or
    // nearly so — or we wait a few ticks on the first frame, which is black.
    // At most half a second, on a screen that was black anyway.
    unsigned int skip = 0, wait_ticks = 0;
    if (loop_len > 0) {
        long long absolute = t0 * fps / 1000;
        unsigned int wanted = (unsigned int)(
                ((absolute + a->loop_start) % loop_len + loop_len) %
                loop_len);
        if (wanted < a->loop_start)
            skip = wanted;
        else
            wait_ticks = loop_len - wanted;
    }

    size_t frame_bytes = (size_t)a->width * a->height;
    unsigned int last = (unsigned int)-1;

    while (!stop_requested) {
        long long now = now_ms();
        if (now >= deadline) break;

        if (still) {
            draw_frame(&s, frames + (size_t)a->loop_start * frame_bytes, NULL,
                       a->width, a->height, x0, y0);
            klog("still: drawn only once, waiting");
            while (!stop_requested && now_ms() < deadline)
                sleep_ms(200);
            break;
        }

        unsigned int n = (unsigned int)((now - t0) * fps / 1000);
        unsigned int idx;
        // Always natural speed: one tick, one frame.
        if (n < wait_ticks) {
            idx = 0;
        } else {
            unsigned int m = n - wait_ticks + skip;

            if (m < a->loop_start)
                idx = m;
            else
                idx = a->loop_start +
                      (m - a->loop_start) % loop_len;
        }
        if (idx != last) {
            draw_frame(&s, frames + (size_t)idx * frame_bytes,
                       on_screen, a->width, a->height, x0, y0);
            last = idx;
        }
        sleep_ms(1000 / (long long)fps);
    }

    // Silent exit, and not out of laziness. By now SELinux has been enforcing
    // for a while and the process is in the `kernel` domain: RMFB and
    // DESTROY_DUMB would be two ioctls on gpu_device, i.e. two denials per
    // boot (measured: ioctlcmd 0x64af and 0x64b4). They are not needed:
    // drm_release frees the framebuffer and the dumb buffer when the last fd
    // is closed, and _exit takes care of closing the fd.
    _exit(0);
}
